### ISSUE TITLE
Create a first release

### ISSUE THREAD

**Issue by gfleury** [gfleury/libnss-iam#5]
Create first release compatible with Ubuntu 16/18 and CentOS/Amazon Linux. 
Release .deb and .rpm packages.

**Comment by gfleury** [comment]
@fred-vogt already added .deb support. Haven't tested yet but seems to work with Ubuntu 16, right @fred-vogt?

I will get sometime to work on a RPM packaging.

**Comment by vogtech** [comment]
@gfleury Confirmed the .deb package works with both Ubuntu 16.04/18.04

**Comment by fred-vogt** [comment]
@gfleury - working on ubuntu-18.04+ support next.

**Comment by gfleury** [comment]
Great work @fred-vogt !!! Let's close this one!

**Comment by gfleury** [comment]
We can focus on rpm for AL later.

**Comment by gfleury** [comment]
@fred-vogt quick question, have we released the .debs? In the release page? I'm from my mobile now and can't check it

**Comment by fred-vogt** [comment]
@gfleury not yet.

**Comment by fred-vogt** [comment]
@gfleury - I can upload them shortly and put up a PR for ubuntu 18-04+.

**Comment by gfleury** [comment]
Ok, that would be great, no hurry.

**Comment by fred-vogt** [comment]
https://github.com/gfleury/libnss-iam/releases/tag/v0.1
